### ISSUE TITLE
Can't use more than 7 bio reader

### ISSUE THREAD

**Issue by Ralileo16** [PC-Logix/OpenSecurity#130]
i'm using 8 bioreader for opening redstone 3x3 doors(they are all working) and whenever i check if all the bioreader are working there's always one that isn't so i break it replace it and use the new address so now that one works but on of the older stops working instead

**Comment by Ralileo16** [comment]
i can provide code https://pastebin.com/QrzVwQTc
and some screenshots too

**Comment by Ralileo16** [comment]
after hours of testing it came to my mind that if only 1 bioreader isnt working then i should add 1 more until that one becomes the not working one so all the others would work just fine and it actually worked at least for now

**Comment by ben-mkiv** [comment]
you are doing `c.os_biometric.setEventName("bio")` at the start of the script which changes the event name for one of the readers to bio instead of bioReader, thats why you wont catch the event from the "first" bioreader anymore, so remove line #3 from your script and everything should work as expected

you could also do something like
```lua
component = require("component")
for address,type in pairs(component.list("os_biometric")) do
  component.proxy(address).setEventName("bio")
end
```
to change the event name for all of them
