### ISSUE TITLE
does not work at all

### ISSUE THREAD

**Issue by globttu** [PC-Logix/OpenSecurity#155]
i can't get any files to come up in my computer

**Comment by CaitlynMainer** [comment]
I'm not sure where to even start with this. What files exactly are you expecting? What are you trying to do? Is the mod correctly installed? Is OpenComputers correctly installed?

**Comment by globttu** [comment]
its says when i have the mod and opencomputers in and i type any cmd in it says no  file with that name

**Comment by globttu** [comment]
and theres nothing to say how to setup files

**Comment by globttu** [comment]
it has no directory files to make mod work like 0 commands work

**Comment by Kristopher38** [comment]
Let me tell you how this works here.
You write what forge, game and mod versions you're running, you write a DETAILED description of what you're doing, for example: "I'm trying to do `<something>`, I made a fresh install of OpenOS on a computer, connected `<something>` components and I'm trying to run a command `xyz` but it fails with an error message `<you paste your error message here>`", not that crap "I type ANY command and it says no file with that name" because that actually tells us very little and yet you expect us to help you. Also GitHub issue page isn't a chatbox, you should write all your message in one comment, not split it into multiple comments, each containing one line. There's even an option to edit your message after you posted it.

**Comment by globttu** [comment]
i can't execute cmds from mods cause it has no folder and btw im using newest 1 of both mods and  1.12.2-forge-14.23.5.2854

**Comment by CaitlynMainer** [comment]
This mod doesn't add any "Commands".  You have to write your own code to interact with this mods components.

**Comment by globttu** [comment]
and the error is only no file

**Comment by globttu** [comment]
im not an coder so i need the code

**Comment by CaitlynMainer** [comment]
Well, OpenComputers, and by extension OpenSecurity are designed around you need it, you write it. So my suggestion would be: You need to learn to code.   You can always check out the OpenComputers forums, specifically the "Program Showcase" sub forum to see if anyone has anything helpful. https://oc.cil.li/forum/34-programs/

Also, hit up our discord: https://discord.gg/bYqKv7h or our IRC Channel on irc.esper.net #oc

**Comment by globttu** [comment]
i have 0 coding expenece

**Comment by Kristopher38** [comment]
That doesn't mean you can't learn how to code. There are plenty of resources on the internet which you can use, such as the one mentioned above to look up examples, or my favourite for beginners: [Lua tutorial](https://www.tutorialspoint.com/lua/index.htm)
I suggest starting there, then moving onto OpenComputers-specific stuff, such as [component interaction](https://ocdoc.cil.li/api:component). As said before, you're gonna need to write the thing you want done yourself, as the mod itself doesn't contain built-in programs, it just allows you to write them.

**Comment by immibis** [comment]
1. What did you do? What keys did you type? What buttons did you press?

2. What was supposed to happen?

3. What actually happened?
