### ISSUE TITLE
Block breaking drop issue

### ISSUE THREAD

**Issue by egorchik007** [PC-Logix/OpenSecurity#22]
Both RFID reader and Card writer can be broken with one hit with hand or item, but they do not drop.
If you break them with a tool, they  do drop.
Didn't test with other blocks.

**Comment by egorchik007** [comment]
Well, it only drops with a pickaxe, to be honest. Shovel doesn't work :P

**Comment by CaitlynMainer** [comment]
This isn't so much a "bug" as an odd side effect.  All of the blocks take Iron as their material, so they require the same tool to break as say an Iron Block.  If you break an iron block with your hand no drop is generated, same here.  This DID point out however that the RFID Reader was extending the wrong class which is why it instantly broke.

**Comment by egorchik007** [comment]
Then please make it long (LONG) to break it with a hand (coz it sucks to break a pricy block by a missclick) and a bit longer with a tool. Just like OpenComputers blocks would be fine.

**Comment by CaitlynMainer** [comment]
-snip- was extending the wrong class which is why it instantly broke.  It's already been fixed.

**Comment by egorchik007** [comment]
Thanks! Nice to have it updated so quickly. 
I am gonna set up modding environment and try to add some features. 
Like energy suck depending on rfid scanning range and a smart chest, that can be looted and taken away(if allowed by owner in unlocked mode) but cannot be opened without providing a key via api.

**Comment by CaitlynMainer** [comment]
Power drain is already implemented locally, I've just not tested it enough to push.

**Comment by egorchik007** [comment]
If you allow that, of course.
There is no license here on this repo.
