### ISSUE TITLE
Rfid scanning range is broken

### ISSUE THREAD

**Issue by egorchik007** [PC-Logix/OpenSecurity#23]
I first though this is really a diameter of scan, but...
(https://pp.vk.me/c625120/v625120648/4228f/E-8rMgiK1j4.jpg)

It's absolutely broken (see minimap).
Sometimes it can find me by setting range=4, but can't at range=20 and so on.

**Comment by CaitlynMainer** [comment]
The range is hard limited to 64, so it's pointless trying any higher then that.

Who has the card? Are you holding it in your inventory? 
How far from the RFID scanner are you?
http://michi.pc-logix.com/Minecraft_1.7.10_2015-07-19_19-40-27.png

If this is in your inventory and you're not moving around, I have no clue what the issue is.  I can't reproduce it in dev, or on my server.

**Comment by CaitlynMainer** [comment]
What is the RFID Range set to in the config? The way the code works is the range you pass in is divided by two.  If the config maximum is 16, and you pass in 17, the scan does 16/2 which gives 8, add 1 for the actual block location which gives you a range of 9 blocks radius, 7 blocks diameter (in a square).  You can see the AABB bounds setting here http://git.io/vmAqJ  and the math here http://git.io/vmAqq

**Comment by CaitlynMainer** [comment]
I'm closing this issue due to lack of information, feel free to comment and reopen if this is an issue.
